id: A49338467
title: A Prayer for the Long Life of Ngawang Kunga Tekchen Palbar Trinlé Wangi Gyalpo,
  the Lord of Refuge and Precious Holder of the Throne of the Drolma Palace at Glorious
  Sakya
type: translation
pechas:
- I30A24032
- IA8B0E7D1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:09.637728
  last_modified_at: 2023-01-04 12:15:09.637735
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I30A24032/7838: CFEB
  IA8B0E7D1/E48E: CFEB
